// front/src/app/button/button.component.ts
import { Component, input, output } from '@angular/core';

@Component({
  selector: 'app-button',
  imports: [],
  templateUrl: './button.component.html',
  styleUrl: './button.component.css',
})
export class ButtonComponent {
  click = output();
  styles = input('');
  label = input('Click me');
  layout = input('');
  disabled = input(false);
}

<div [class]="layout()">
  <button
    [class]="
      [
        'bg-blue-500',
        'hover:bg-blue-600',
        'text-white',
        'font-semibold',
        'py-2',
        'px-4',
        'rounded-full',
        'shadow',
        'transition',
        'duration-300',
        'ease-in-out',
        'transform',
        'hover:scale-105'
      ].concat(styles().split(' '))
    "
    [disabled]="disabled()"
  >
    <div class="flex items-center">
      <ng-content />
    </div>
  </button>
</div>

// front/components/button.vue
<script setup lang="ts">
import { defineProps } from "vue";

withDefaults(
  defineProps<{
    click?: () => void;
    styles?: string;
    label?: string;
    layout?: string;
  }>(),
  {
    click: () => {},
    styles: "",
    label: "Click me",
    layout: "",
  }
);
</script>

<template>
  <div :class="layout">
    <button
      @click="click"
      :class="[
        'bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-full shadow transition duration-300 ease-in-out transform hover:scale-105',
        styles,
      ]"
    >
      <div class="flex items-center">
        <slot></slot>
      </div>
    </button>
  </div>
</template>
