// front/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { ButtonComponent } from '../button/button.component';
import { UserService } from '../services/user.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, ButtonComponent, CommonModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css',
})
export class NavbarComponent implements OnInit {
  menuItems: { path: string; label: string }[] = [];

  constructor(public userService: UserService, private router: Router) {
    this.userService.user$.subscribe(() => {
      this.menuItems = this.userService.getMenuItems();
    });
  }

  ngOnInit(): void {
    this.menuItems = this.userService.getMenuItems();
  }

  logOut() {
    this.userService.logOut();
  }
}

<div
  class="p-2 flex w-full items-center justify-between bg-white border-b-2 border-blue-300 shadow-2xl"
>
  <div class="flex items-center">
    <a routerLink="/" class="w-16 h-16 me-4">
      <img
        src="/logo.webp"
        alt="Description"
        class="rounded-full border-gray-300 object-cover w-full h-full"
      />
    </a>
    
    @if (userService.getUser()) {
      <nav class="flex items-center gap-4">
        @for (item of menuItems; track item.path) {
          <a [routerLink]="item.path" routerLinkActive="text-blue-600 font-bold">
            <app-button layout="pe-2">{{ item.label }}</app-button>
          </a>
        }
      </nav>
    }
  </div>

  <div class="flex items-center gap-4">
    @if (userService.getUser()) {
      <div class="flex items-center gap-2">
        <span class="text-sm font-medium">
          {{ userService.getRolLabel(userService.getUser()?.rol || '') }}:
        </span>
        <span class="font-bold">{{ userService.getUser()?.username }}</span>
      </div>

      <app-button layout="pe-2" (click)="logOut()">
        <svg
          class="me-2"
          stroke="currentColor"
          fill="currentColor"
          stroke-width="0"
          viewBox="0 0 24 24"
          height="25px"
          width="25px"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path fill="none" d="M0 0h24v24H0z"></path>
          <path
            d="M11 7 9.6 8.4l2.6 2.6H2v2h10.2l-2.6 2.6L11 17l5-5-5-5zm9 12h-8v2h8c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-8v2h8v14z"
          ></path>
        </svg>
        Cerrar Sesión
      </app-button>
    } @else {
      <div class="flex items-center gap-2">
        <a routerLink="/login">
          <app-button layout="pe-2">
            <svg
              class="me-2"
              stroke="currentColor"
              fill="currentColor"
              stroke-width="0"
              viewBox="0 0 24 24"
              height="25px"
              width="25px"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path fill="none" d="M0 0h24v24H0z"></path>
              <path
                d="M11 7 9.6 8.4l2.6 2.6H2v2h10.2l-2.6 2.6L11 17l5-5-5-5zm9 12h-8v2h8c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-8v2h8v14z"
              ></path>
            </svg>
            Iniciar Sesión
          </app-button>
        </a>
        <a routerLink="/signup">
          <app-button>
            <svg
              class="pe-2"
              stroke="currentColor"
              fill="currentColor"
              stroke-width="0"
              viewBox="0 0 512 512"
              height="25px"
              width="25px"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M512 176.001C512 273.203 433.202 352 336 352c-11.22 0-22.19-1.062-32.827-3.069l-24.012 27.014A23.999 23.999 0 0 1 261.223 384H224v40c0 13.255-10.745 24-24 24h-40v40c0 13.255-10.745 24-24 24H24c-13.255 0-24-10.745-24-24v-78.059c0-6.365 2.529-12.47 7.029-16.971l161.802-161.802C163.108 213.814 160 195.271 160 176 160 78.798 238.797.001 335.999 0 433.488-.001 512 78.511 512 176.001zM336 128c0 26.51 21.49 48 48 48s48-21.49 48-48-21.49-48-48-48-48 21.49-48 48z"
              ></path>
            </svg>
            Registrarse
          </app-button>
        </a>
      </div>
    }
  </div>
</div>

// front/components/navbar.vue
<script setup lang="ts">
import Switch from "./switch.vue";
const edit = useEdit()
</script>

<template>
  <div
    class="p-2 flex w-full items-center bg-white border-b-2 border-blue-300 shadow-2xl"
  >
    <NuxtLink to="/" class="w-16 h-16 me-2">
      <img
        src="public/logo.webp"
        alt="Description"
        class="rounded-full border-gray-300 object-cover w-full h-full"
      />     
    </NuxtLink>
    <Switch :onchange="(event:Event) => {
      edit = (event.target as HTMLInputElement)?.checked;
      console.log(edit)
    }" />
    <NuxtLink to="/login">
      <Button layout="pe-2">
        <svg
          class="me-2"
          stroke="currentColor"
          fill="currentColor"
          stroke-width="0"
          viewBox="0 0 24 24"
          height="25px"
          width="25px"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path fill="none" d="M0 0h24v24H0z"></path>
          <path
            d="M11 7 9.6 8.4l2.6 2.6H2v2h10.2l-2.6 2.6L11 17l5-5-5-5zm9 12h-8v2h8c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-8v2h8v14z"
          ></path>
        </svg>
        Log In
      </Button>
    </NuxtLink>
    <NuxtLink to="/signup">
      <Button>
        <svg
          class="pe-2"
          stroke="currentColor"
          fill="currentColor"
          stroke-width="0"
          viewBox="0 0 512 512"
          height="25px"
          width="25px"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M512 176.001C512 273.203 433.202 352 336 352c-11.22 0-22.19-1.062-32.827-3.069l-24.012 27.014A23.999 23.999 0 0 1 261.223 384H224v40c0 13.255-10.745 24-24 24h-40v40c0 13.255-10.745 24-24 24H24c-13.255 0-24-10.745-24-24v-78.059c0-6.365 2.529-12.47 7.029-16.971l161.802-161.802C163.108 213.814 160 195.271 160 176 160 78.798 238.797.001 335.999 0 433.488-.001 512 78.511 512 176.001zM336 128c0 26.51 21.49 48 48 48s48-21.49 48-48-21.49-48-48-48-48 21.49-48 48z"
          ></path>
        </svg>
        Sign Up
      </Button>
    </NuxtLink>
  </div>
</template>
